#!/usr/bin/env python3
# png2bitmap_rgb565_c_h_pragonce.py
# Convert PNG → RGB565 .c + .h files for:
# struct bitmap { uint16_t width; uint16_t height; uint16_t* bitmap; }
# Symbols are prefixed with the PNG filename (without extension)
# .h uses #pragma once instead of include guards

import argparse
import os
import struct
from PIL import Image


def pack_rgb565(r, g, b):
    """RGB888 → RGB565 (5-6-5)"""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def image_to_rgb565_words(img):
    rgba = img.convert("RGBA")
    w, h = rgba.size
    px = rgba.load()
    words = []
    for y in range(h):  # top→down
        for x in range(w):
            r, g, b, a = px[x, y]
            words.append(pack_rgb565(r, g, b))
    return w, h, words


def write_h_file(path, prefix):
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Generated by png2bitmap_rgb565_c_h_pragonce.py\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("typedef struct bitmap {\n"
                "    uint16_t width;\n"
                "    uint16_t height;\n"
                "    uint16_t* bitmap;\n"
                "} bitmap;\n\n")
        f.write(f"extern const bitmap {prefix}_bitmap;\n")


def write_c_file(path, header_name, prefix, w, h, words):
    total = len(words)
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Generated by png2bitmap_rgb565_c_h_pragonce.py\n")
        f.write("#include <stdint.h>\n")
        f.write(f"#include \"{header_name}\"\n\n")
        f.write(f"// {w}x{h}, RGB565 format\n")
        f.write(f"static const uint16_t {prefix}_pixels[{total}] = {{\n  ")
        for i, v in enumerate(words):
            end = ", " if i + 1 < total else ""
            if (i + 1) % 12 == 0 and (i + 1) < total:
                f.write(f"0x{v:04x}{end}\n  ")
            else:
                f.write(f"0x{v:04x}{end}")
        f.write("\n};\n\n")
        f.write(f"const bitmap {prefix}_bitmap = {{ {w}, {h}, (uint16_t*){prefix}_pixels }};\n")


def main():
    ap = argparse.ArgumentParser(description="PNG → RGB565 .c + .h generator (symbols use PNG filename prefix, #pragma once).")
    ap.add_argument("input", help="input .png file")
    ap.add_argument("--out-c", help="output .c filename (default: <input>.c)")
    ap.add_argument("--out-h", help="output .h filename (default: <input>.h)")
    args = ap.parse_args()

    img = Image.open(args.input)
    w, h, words = image_to_rgb565_words(img)

    base, _ = os.path.splitext(os.path.basename(args.input))
    prefix = base.replace("-", "_").replace(" ", "_")

    out_c = args.out_c or f"{base}.c"
    out_h = args.out_h or f"{base}.h"
    header_name = os.path.basename(out_h)

    write_h_file(out_h, prefix)
    write_c_file(out_c, header_name, prefix, w, h, words)

    print(f"Wrote {out_c} ({w}x{h}, RGB565, {len(words)} pixels)")
    print(f"Wrote {out_h} (header for {prefix}_bitmap, using #pragma once)")


if __name__ == "__main__":
    main()
